blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/core/urls.py
from django.urls import path
from . import views


app_name = 'core'


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag')
]

blog/core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
from taggit_autosuggest.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликовано'),
    )
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    image = models.ImageField(upload_to='images/%y', blank=False, null=False)
    body = RichTextUploadingField()
    tags = TaggableManager()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    views = models.PositiveIntegerField(default=0)

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('core:post_detail', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/core/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/core/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from taggit.models import Tag


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 10)  # По 3 статьи на каждой странице.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц, возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')

    if request.method == 'GET':
        post.views += 1
        post.save()
        return render(request, 'blog/detail.html', {'post': post})

blog/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <div class="container header">
            <div class="header__logo">
                <a href="/">Coding Blog</a>
            </div>
        </div>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer>
        <div class="container footer">
            <a href="mailto:classsikpartnership@gmail.com" class="copyright">Classsik © 2021</a>
        </div>
    </footer>
</body>

</html>

blog/core/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<main>
  <h1 class="title">{{ post.title }}</h1>
  <div class="post-data">
    <p>{{ post.publish|date }}</p>
    <p class="views">
      <svg xmlns="http://www.w3.org/2000/svg" class="" viewBox="0 0 20 20" fill="currentColor">
        <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
        <path fill-rule="evenodd"
          d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z"
          clip-rule="evenodd" />
      </svg>
      {{post.views}}
    </p>
    {% for tag in post.tags.all %}
    <a href="{% url 'core:post_list_by_tag' tag.slug %}">
      #{{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
  </div>

  <div class="post">
    {{ post.body|safe }}
  </div>
</main>


<div id="disqus_thread"></div>
<script>
  (function () {
    var d = document, s = d.createElement('script');
    s.src = 'https://blog-auaxcnjnia.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
    Disqus.</a></noscript>
{% endblock %}

blog/core/templates/blog/list.html
{% extends "base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
{% if tag %}
<h1 class="title-tag">#{{ tag.name }}</h1>
{% endif %}
<div class="row">
    {% for post in posts %}
    <div class="card">
        <a href="{{ post.get_absolute_url }}">
            <img src="{{post.image.url}}" alt="" class="post-image">
            <div class="card-body">
                <div class="tags">
                    {% for tag in post.tags.all %}
                    <p class="post-tag">
                        #{{ tag.name }}
                    </p>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </div>
                <h2 class="post-title">{{ post.title }}</h2>
                {{ post.body|safe|truncatewords:12 }}
                <time class="post-date">{{ post.publish|date }}</time>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

{% include "pagination.html" with page=posts %}
{% endblock %}

blog/core/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}">Назад</a>
    {% endif %}
    <span class="current">
      Страница {{ page.number }} из {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Вперед</a>
    {% endif %}
  </span>
</div>